In [2]:
import numpy as np

Numpy Indexing Slicing Boolean Index Fancy Index

1. Boolean Indexing

Boolean indexing is basically a method to return a return a new array depending upon the condition specified. It basically allows us to select elements based on a condition. It returns a new array with elements that match the condition.

In [3]:
a = np.array([10, 20, 30, 40, 50])
condition = a > 25
print(condition)       
print(a[condition])    

#More better way
print(a[a < 40])     


[False False  True  True  True]
[30 40 50]
[10 20 30]


2. Fancy Indexing

Fancy indexing means using arrays or lists of indices to pick specific elements in a custom order.

In [4]:
a = np.array([10, 20, 30, 40, 50])
indices = [0, 3, 4]
print(a[indices])      

# On 2D arrays
b = np.array([[1, 2], [3, 4], [5, 6]])
print(b[[0, 2]])       # Select rows 0 and 2 → [[1, 2], [5, 6]]
print(b[[0, 2], [0,1]])       # Select rows 0, column 0 and row 2, column 1 → [1, 6]


[10 40 50]
[[1 2]
 [5 6]]
[1 6]
